import type { CatalogMeal } from '../meal-catalog';

/**
 * Les plats de l'objectif « prise de masse ».
 *
 * La difficulté ici est inverse de celle de la perte : il faut faire entrer
 * beaucoup de calories dans un volume qu'on puisse avaler trois fois par jour.
 * D'où les huiles, les oléagineux et les sauces, qui apportent sans remplir,
 * et des féculents plutôt que des légumes en masse.
 *
 * Les estimations sont recalculées par `npm run verify:catalog` (voir
 * `meal-catalog.ts`). Ne pas les corriger à la main.
 */
export const CATALOG_GAIN: readonly CatalogMeal[] = [
  {
    slug: 'gain-porridge-banane-noix',
    name: 'Porridge complet banane et cacahuète',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 10,
    steps: [
      'Porter le lait entier à frémissement, y verser les flocons d’avoine.',
      'Cuire 6 minutes en remuant, le porridge doit napper la cuillère.',
      'Écraser la banane dedans hors du feu, ajouter le beurre de cacahuète et le miel.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 90 },
      { label: 'Lait entier', searchTerm: 'lait entier', quantityG: 300 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 150, unitName: 'banane', unitGrams: 150 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 30 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 20 },
    ],
    estimate: { kcal: 916, proteinG: 28 },
  },
  {
    slug: 'gain-oeufs-avocat-pain',
    name: 'Œufs brouillés, avocat et pain grillé',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 12,
    steps: [
      'Battre les œufs, les cuire au beurre à feu très doux, 5 minutes, sans cesser de remuer.',
      'Ajouter l’emmental en fin de cuisson, il doit fondre sans cuire.',
      'Griller le pain, y écraser l’avocat, poser les œufs dessus.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 180, unitName: 'œuf', unitGrams: 60 },
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 100 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 100 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 15 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 30 },
    ],
    estimate: { kcal: 931, proteinG: 40 },
  },
  {
    slug: 'gain-bowl-yaourt-fruits-secs',
    name: 'Bol de yaourt grec, avoine et fruits secs',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 5,
    steps: [
      'Mélanger l’avoine au yaourt, laisser dix minutes.',
      'Ajouter amandes concassées et raisins secs.',
      'Filer le miel juste avant de manger.',
    ],
    ingredients: [
      { label: 'Yaourt grec nature', searchTerm: 'yaourt grec nature', quantityG: 250 },
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 70 },
      { label: 'Amandes', searchTerm: 'amande emondee', quantityG: 30 },
      { label: 'Raisins secs', searchTerm: 'raisin sec', quantityG: 30 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 20 },
    ],
    estimate: { kcal: 868, proteinG: 22 },
  },
  {
    slug: 'gain-pancakes-avoine-banane',
    name: 'Pancakes avoine et banane',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 15,
    steps: [
      'Mixer flocons d’avoine, œufs, lait et la moitié de la banane.',
      'Laisser reposer la pâte 5 minutes, elle doit épaissir.',
      'Cuire de petites louches 2 minutes par face dans un peu d’huile.',
      'Napper de beurre de cacahuète fondu, garnir du reste de banane.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 90 },
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 150, unitName: 'œuf', unitGrams: 50 },
      { label: 'Lait entier', searchTerm: 'lait entier', quantityG: 200 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 120, unitName: 'banane', unitGrams: 120 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 15 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 5 },
    ],
    estimate: { kcal: 918, proteinG: 40 },
  },
  {
    slug: 'gain-tartines-saumon-fume',
    name: 'Tartines au saumon fumé et avocat',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 8,
    steps: [
      'Griller les tranches de pain.',
      'Battre le fromage blanc avec le jus de citron, l’étaler sur le pain.',
      'Poser le saumon fumé et les lamelles d’avocat, poivrer largement.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 120 },
      { label: 'Saumon fumé', searchTerm: 'saumon fume', quantityG: 120 },
      { label: 'Fromage blanc 3 %', searchTerm: 'fromage blanc 3', quantityG: 100 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 80 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 15 },
    ],
    estimate: { kcal: 767, proteinG: 44 },
  },
  {
    slug: 'gain-poulet-riz-complet-avocat',
    name: 'Poulet, riz complet et avocat',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Mettre le riz complet à cuire, 20 minutes.',
      'Saisir les filets de poulet 5 minutes par face, les laisser reposer avant de trancher.',
      'Poêler les poivrons en lanières 8 minutes à l’huile d’olive.',
      'Dresser, ajouter l’avocat en lamelles au dernier moment.',
    ],
    ingredients: [
      { label: 'Filets de poulet', searchTerm: 'filet de poulet cuit a la poele', quantityG: 320 },
      { label: 'Riz complet', searchTerm: 'riz complet cuit', quantityG: 450 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 150 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 25 },
    ],
    estimate: { kcal: 933, proteinG: 59 },
  },
  {
    slug: 'gain-pates-boeuf-parmesan',
    name: 'Pâtes au bœuf et parmesan',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre les pâtes à cuire dans un grand volume d’eau salée.',
      'Saisir la viande hachée à feu vif, l’émietter à la spatule.',
      'Verser les tomates pelées, mijoter 15 minutes à découvert.',
      'Mélanger aux pâtes avec l’huile d’olive, râper le parmesan par-dessus.',
    ],
    ingredients: [
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 500 },
      { label: 'Bœuf haché 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 300 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 250 },
      { label: 'Parmesan', searchTerm: 'parmesan', quantityG: 50 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 25 },
    ],
    estimate: { kcal: 916, proteinG: 66 },
  },
  {
    slug: 'gain-chili-boeuf-riz',
    name: 'Chili de bœuf, haricots rouges et riz',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Saisir la viande hachée, l’émietter, réserver.',
      'Faire revenir les tomates pelées 10 minutes à l’huile d’olive.',
      'Remettre la viande, ajouter les haricots rouges rincés, mijoter 15 minutes.',
      'Servir sur le riz, couvrir d’emmental râpé qui fondra tout seul.',
    ],
    ingredients: [
      { label: 'Bœuf haché 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 300 },
      { label: 'Haricots rouges', searchTerm: 'haricot rouge cuit', quantityG: 400 },
      { label: 'Riz blanc', searchTerm: 'riz blanc cuit', quantityG: 400 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 250 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 60 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 995, proteinG: 73 },
  },
  {
    slug: 'gain-saumon-quinoa-feta',
    name: 'Saumon, quinoa et brocolis à la feta',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Cuire le quinoa 15 minutes dans deux fois son volume d’eau.',
      'Cuire les brocolis 8 minutes à la vapeur.',
      'Poêler les pavés de saumon 5 minutes côté peau, 2 minutes de l’autre.',
      'Mélanger quinoa, brocolis et huile d’olive, émietter la feta dessus.',
    ],
    ingredients: [
      { label: 'Pavés de saumon', searchTerm: 'saumon pave cuit', quantityG: 300 },
      { label: 'Quinoa', searchTerm: 'quinoa cuit', quantityG: 450 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 300 },
      { label: 'Feta', searchTerm: 'feta', quantityG: 80 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 25 },
    ],
    estimate: { kcal: 926, proteinG: 58 },
  },
  {
    slug: 'gain-couscous-poulet-pois-chiches',
    name: 'Couscous poulet et pois chiches',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 40,
    steps: [
      'Faire dorer les cuisses de poulet, réserver.',
      'Cuire carottes et courgettes en gros tronçons 20 minutes dans un bouillon.',
      'Ajouter les pois chiches, remettre le poulet, 10 minutes de plus.',
      'Verser l’eau bouillante sur la semoule, couvrir 5 minutes, égrener à la fourchette.',
    ],
    ingredients: [
      { label: 'Cuisses de poulet', searchTerm: 'poulet roti viande', quantityG: 320 },
      { label: 'Semoule', searchTerm: 'semoule cuite', quantityG: 400 },
      { label: 'Pois chiches', searchTerm: 'pois chiche cuit', quantityG: 300 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 200 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 25 },
    ],
    estimate: { kcal: 982, proteinG: 66 },
  },
  {
    slug: 'gain-bowl-boeuf-patate-douce',
    name: 'Bowl bœuf, patate douce et noix de cajou',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Préchauffer le four à 200 °C, enfourner les patates douces en cubes huilés, 25 minutes.',
      'Saisir la viande hachée à feu vif, la saler en fin de cuisson.',
      'Faire tomber les épinards 3 minutes.',
      'Dresser en bol, ajouter l’avocat en lamelles et les noix de cajou concassées.',
    ],
    ingredients: [
      { label: 'Bœuf haché 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 300 },
      { label: 'Patates douces', searchTerm: 'patate douce cuite', quantityG: 600 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 250 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 120 },
      { label: 'Noix de cajou', searchTerm: 'noix de cajou', quantityG: 40 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 25 },
    ],
    estimate: { kcal: 855, proteinG: 51 },
  },
  {
    slug: 'gain-gratin-pates-thon',
    name: 'Gratin de pâtes au thon',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Cuire les pâtes une minute de moins que le temps indiqué : elles finiront au four.',
      'Mélanger la crème, les tomates pelées et le thon égoutté.',
      'Réunir avec les pâtes dans un plat, couvrir d’emmental.',
      'Enfourner 20 minutes à 200 °C.',
    ],
    ingredients: [
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 450 },
      { label: 'Thon au naturel', searchTerm: 'thon au naturel', quantityG: 250 },
      { label: 'Crème épaisse', searchTerm: 'creme fraiche epaisse', quantityG: 100 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 70 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 200 },
    ],
    estimate: { kcal: 869, proteinG: 62 },
  },
  {
    slug: 'gain-porc-pommes-de-terre',
    name: 'Filet mignon, pommes de terre et haricots verts',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 40,
    steps: [
      'Saisir le filet mignon sur toutes ses faces, l’enfourner 20 minutes à 180 °C.',
      'Cuire les pommes de terre 20 minutes à l’eau salée, les faire ensuite rissoler au beurre.',
      'Cuire les haricots verts 8 minutes à la vapeur.',
      'Déglacer la poêle à la crème, en napper la viande tranchée.',
    ],
    ingredients: [
      { label: 'Filet mignon de porc', searchTerm: 'porc filet mignon cuit', quantityG: 320 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 600 },
      { label: 'Haricots verts', searchTerm: 'haricot vert cuit', quantityG: 300 },
      { label: 'Crème épaisse', searchTerm: 'creme fraiche epaisse', quantityG: 60 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 25 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 803, proteinG: 51 },
  },
  {
    slug: 'gain-risotto-poulet-parmesan',
    name: 'Risotto de poulet aux champignons',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Faire revenir les champignons émincés 8 minutes, réserver.',
      'Nacrer le riz à l’huile d’olive, mouiller louche après louche de bouillon chaud.',
      'Au bout de 18 minutes, ajouter la crème de soja et le parmesan hors du feu.',
      'Mélanger le poulet poêlé coupé en cubes et les champignons.',
    ],
    ingredients: [
      { label: 'Riz blanc', searchTerm: 'riz blanc cuit', quantityG: 450 },
      { label: 'Filets de poulet', searchTerm: 'filet de poulet cuit a la poele', quantityG: 300 },
      { label: 'Parmesan', searchTerm: 'parmesan', quantityG: 50 },
      { label: 'Crème de soja', searchTerm: 'creme de soja', quantityG: 100 },
      { label: 'Champignons de Paris', searchTerm: 'champignon de paris cru', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 850, proteinG: 64 },
  },
  {
    slug: 'gain-gratin-dauphinois-jambon',
    name: 'Gratin de pommes de terre au jambon',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 55,
    steps: [
      'Trancher les pommes de terre en rondelles fines, sans les rincer : l’amidon lie le gratin.',
      'Chauffer lait et crème avec de l’ail, saler, muscader.',
      'Alterner pommes de terre et jambon en dés dans le plat, napper.',
      'Enfourner 45 minutes à 180 °C, couvrir d’emmental pour les 10 dernières minutes.',
    ],
    ingredients: [
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 600 },
      { label: 'Crème épaisse', searchTerm: 'creme fraiche epaisse', quantityG: 150 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 80 },
      { label: 'Jambon blanc', searchTerm: 'jambon cuit decouenne tranche', quantityG: 200 },
      { label: 'Lait entier', searchTerm: 'lait entier', quantityG: 150 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 20 },
    ],
    estimate: { kcal: 845, proteinG: 41 },
  },
  {
    slug: 'gain-curry-poulet-riz-complet',
    name: 'Curry de poulet, coco et riz complet',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Mettre le riz complet à cuire, 20 minutes.',
      'Faire revenir l’oignon, ajouter le curry, laisser griller 30 secondes.',
      'Saisir le poulet, verser le lait de coco et les poivrons.',
      'Mijoter 20 minutes à découvert, la sauce doit napper.',
    ],
    ingredients: [
      { label: 'Cuisses de poulet', searchTerm: 'poulet roti viande', quantityG: 320 },
      { label: 'Lait de coco', searchTerm: 'lait de coco', quantityG: 250 },
      { label: 'Riz complet', searchTerm: 'riz complet cuit', quantityG: 400 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 200 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 100 },
      { label: 'Curry en poudre', searchTerm: 'curry poudre', quantityG: 10 },
    ],
    estimate: { kcal: 953, proteinG: 52 },
  },
  {
    slug: 'gain-saumon-pates-epinards',
    name: 'Pâtes crémeuses au saumon et épinards',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre les pâtes à cuire.',
      'Faire tomber les épinards 3 minutes, ajouter la crème, laisser réduire 5 minutes.',
      'Poêler le saumon, l’effeuiller en gros morceaux dans la sauce.',
      'Mélanger aux pâtes, râper le parmesan par-dessus.',
    ],
    ingredients: [
      { label: 'Pavés de saumon', searchTerm: 'saumon pave cuit', quantityG: 280 },
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 450 },
      { label: 'Crème épaisse', searchTerm: 'creme fraiche epaisse', quantityG: 120 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 250 },
      { label: 'Parmesan', searchTerm: 'parmesan', quantityG: 40 },
    ],
    estimate: { kcal: 967, proteinG: 61 },
  },
  {
    slug: 'gain-burger-maison-patate-douce',
    name: 'Burger maison et frites de patate douce',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Tailler les patates douces en bâtonnets, les huiler, les enfourner 30 minutes à 210 °C.',
      'Saisir les steaks 2 minutes par face, poser l’emmental dessus pour qu’il fonde.',
      'Griller les tranches de pain à sec dans la poêle.',
      'Monter les burgers et servir sans attendre.',
    ],
    ingredients: [
      { label: 'Steaks hachés 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 300 },
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 200 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 60 },
      { label: 'Patates douces', searchTerm: 'patate douce cuite', quantityG: 500 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 884, proteinG: 58 },
  },
  {
    slug: 'gain-omelette-lardons-pommes-terre',
    name: 'Omelette aux lardons et pommes de terre',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Faire dorer les lardons à sec, réserver leur gras dans la poêle.',
      'Y rissoler les pommes de terre en rondelles, 15 minutes.',
      'Verser les œufs battus, remettre les lardons, parsemer d’emmental.',
      'Cuire 6 minutes à couvert, servir avec le pain.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 300, unitName: 'œuf', unitGrams: 60 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 500 },
      { label: 'Lardons fumés', searchTerm: 'lardon fume', quantityG: 100 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 60 },
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 120 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 878, proteinG: 45 },
  },
  {
    slug: 'gain-tofu-nouilles-cacahuete',
    name: 'Nouilles au tofu, sauce cacahuète',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre les pâtes à cuire.',
      'Saisir le tofu en cubes 8 minutes à l’huile de colza, jusqu’à ce qu’il dore.',
      'Détendre le beurre de cacahuète avec un peu d’eau de cuisson, pour obtenir une sauce lisse.',
      'Mélanger pâtes, tofu, brocolis et sauce, parsemer de sésame.',
    ],
    ingredients: [
      { label: 'Tofu nature', searchTerm: 'tofu nature', quantityG: 350 },
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 400 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 50 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 300 },
      { label: 'Graines de sésame', searchTerm: 'sesame graine', quantityG: 20 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 20 },
    ],
    estimate: { kcal: 984, proteinG: 52 },
  },
  {
    slug: 'gain-chili-vegetarien-avocat',
    name: 'Chili végétarien à l’avocat',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Faire revenir les tomates pelées à l’huile d’olive, 10 minutes.',
      'Ajouter haricots rouges et pois chiches rincés, mijoter 15 minutes.',
      'Servir sur le riz complet.',
      'Poser l’avocat en lamelles au dernier moment, il ne doit pas cuire.',
    ],
    ingredients: [
      { label: 'Haricots rouges', searchTerm: 'haricot rouge cuit', quantityG: 400 },
      { label: 'Pois chiches', searchTerm: 'pois chiche cuit', quantityG: 250 },
      { label: 'Riz complet', searchTerm: 'riz complet cuit', quantityG: 300 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 150 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 250 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 960, proteinG: 38 },
  },
  {
    slug: 'gain-shake-banane-cacahuete',
    name: 'Shake banane et cacahuète',
    slot: 'snack',
    servings: 1,
    prepMinutes: 3,
    steps: [
      'Mixer tous les ingrédients jusqu’à obtenir une texture lisse.',
      'Boire dans la demi-heure : l’avoine continue de gonfler et le shake s’épaissit.',
    ],
    ingredients: [
      { label: 'Lait entier', searchTerm: 'lait entier', quantityG: 300 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 150, unitName: 'banane', unitGrams: 150 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 30 },
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 40 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 15 },
    ],
    estimate: { kcal: 715, proteinG: 23 },
  },
  {
    slug: 'gain-tartines-cacahuete-miel',
    name: 'Tartines cacahuète, miel et banane',
    slot: 'snack',
    servings: 1,
    prepMinutes: 3,
    steps: [
      'Griller le pain.',
      'Y étaler le beurre de cacahuète, poser les rondelles de banane, filer le miel.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 100 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 40 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 15 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 100, unitName: 'banane', unitGrams: 100 },
    ],
    estimate: { kcal: 647, proteinG: 18 },
  },
  {
    slug: 'gain-yaourt-noix-chocolat',
    name: 'Yaourt grec, noix et chocolat noir',
    slot: 'snack',
    servings: 1,
    prepMinutes: 2,
    steps: [
      'Concasser les noix et le chocolat au couteau.',
      'Les mélanger au yaourt, filer le miel par-dessus.',
    ],
    ingredients: [
      { label: 'Yaourt grec nature', searchTerm: 'yaourt grec nature', quantityG: 200 },
      { label: 'Cerneaux de noix', searchTerm: 'noix cerneaux', quantityG: 30 },
      { label: 'Chocolat noir 70 %', searchTerm: 'chocolat noir 70% cacao', quantityG: 25 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 10 },
    ],
    estimate: { kcal: 600, proteinG: 13 },
  },
];
