import type { CatalogMeal } from '../meal-catalog';

/**
 * Les plats de l'objectif « perte de poids ».
 *
 * Le fil conducteur est le volume à calories égales : beaucoup de légumes,
 * une source de protéines à chaque repas, et des féculents présents mais
 * mesurés. Un plat de régime qui laisse sur sa faim n'est pas tenu une
 * semaine, et la semaine est l'unité qui compte ici.
 *
 * Les estimations sont recalculées par `npm run verify:catalog` (voir
 * `meal-catalog.ts`). Ne pas les corriger à la main.
 */
export const CATALOG_LOSE: readonly CatalogMeal[] = [
  {
    slug: 'lose-avoine-fruits-rouges',
    name: 'Avoine froide, fromage blanc et fruits rouges',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 5,
    steps: [
      'Mélanger les flocons d’avoine au fromage blanc dans un bol.',
      'Laisser dix minutes le temps que l’avoine s’attendrisse, ou toute la nuit au frais.',
      'Couvrir de fruits rouges et d’amandes concassées au moment de manger.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 40 },
      { label: 'Fromage blanc 0 %', searchTerm: 'fromage blanc 0', quantityG: 200 },
      { label: 'Framboises', searchTerm: 'framboise crue', quantityG: 80 },
      { label: 'Myrtilles', searchTerm: 'myrtille crue', quantityG: 40 },
      { label: 'Amandes', searchTerm: 'amande emondee', quantityG: 10 },
    ],
    estimate: { kcal: 369, proteinG: 22 },
  },
  {
    slug: 'lose-omelette-champignons-epinards',
    name: 'Omelette aux champignons et épinards',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 10,
    steps: [
      'Faire tomber les champignons émincés à la poêle, 5 minutes, sans matière grasse.',
      'Ajouter les épinards, laisser rendre leur eau 2 minutes.',
      'Verser les œufs battus, cuire 3 minutes à feu doux, plier l’omelette.',
      'Servir avec la tranche de pain de campagne.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 120, unitName: 'œuf', unitGrams: 60 },
      { label: 'Champignons de Paris', searchTerm: 'champignon de paris cru', quantityG: 100 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 100 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 5 },
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 40 },
    ],
    estimate: { kcal: 355, proteinG: 24 },
  },
  {
    slug: 'lose-porridge-pomme-cannelle',
    name: 'Porridge pomme-cannelle',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 8,
    steps: [
      'Porter le lait à frémissement, y verser les flocons d’avoine.',
      'Cuire 5 minutes en remuant, jusqu’à ce que le mélange épaississe.',
      'Ajouter la pomme coupée en dés et la cannelle, hors du feu.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 50 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 200 },
      { label: 'Pomme', searchTerm: 'pomme crue', quantityG: 130, unitName: 'pomme', unitGrams: 130 },
      { label: 'Cannelle', searchTerm: 'cannelle', quantityG: 2 },
    ],
    estimate: { kcal: 355, proteinG: 13 },
  },
  {
    slug: 'lose-yaourt-grec-kiwi',
    name: 'Yaourt grec, kiwi et amandes',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 5,
    steps: [
      'Verser le yaourt dans un bol.',
      'Peler les kiwis, les couper en rondelles, les disposer dessus.',
      'Parsemer d’amandes concassées et filer le miel.',
    ],
    ingredients: [
      { label: 'Yaourt grec nature', searchTerm: 'yaourt grec nature', quantityG: 150 },
      { label: 'Kiwis', searchTerm: 'kiwi cru', quantityG: 120, unitName: 'kiwi', unitGrams: 60 },
      { label: 'Amandes', searchTerm: 'amande emondee', quantityG: 15 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 10 },
    ],
    estimate: { kcal: 355, proteinG: 9 },
  },
  {
    slug: 'lose-pain-oeufs-avocat',
    name: 'Tartine d’œufs durs et avocat',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 12,
    steps: [
      'Cuire les œufs 9 minutes à l’eau bouillante, les rafraîchir, les écaler.',
      'Écraser l’avocat à la fourchette sur le pain grillé, saler et poivrer.',
      'Disposer les œufs en rondelles et les tranches de tomate par-dessus.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 60 },
      { label: 'Œufs', searchTerm: 'oeuf dur', quantityG: 100, unitName: 'œuf', unitGrams: 50 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 50 },
      { label: 'Tomate', searchTerm: 'tomate rouge crue', quantityG: 80 },
    ],
    estimate: { kcal: 401, proteinG: 19 },
  },
  {
    slug: 'lose-poulet-quinoa-courgettes',
    name: 'Poulet, quinoa et courgettes au citron',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Rincer le quinoa, le cuire 15 minutes dans deux fois son volume d’eau salée.',
      'Couper les courgettes en demi-rondelles, les saisir 8 minutes à l’huile d’olive.',
      'Poêler les filets de poulet 5 minutes de chaque côté, les trancher.',
      'Mélanger le tout, arroser de jus de citron, poivrer généreusement.',
    ],
    ingredients: [
      { label: 'Filets de poulet', searchTerm: 'filet de poulet cuit a la poele', quantityG: 260 },
      { label: 'Quinoa', searchTerm: 'quinoa cuit', quantityG: 300 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 300 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 20 },
    ],
    estimate: { kcal: 500, proteinG: 48 },
  },
  {
    slug: 'lose-salade-thon-haricots-blancs',
    name: 'Salade de thon et haricots blancs',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 15,
    steps: [
      'Rincer et égoutter les haricots blancs.',
      'Couper les tomates en quartiers, émincer l’oignon très finement.',
      'Mélanger avec le thon égoutté, l’huile et le vinaigre. Laisser reposer 10 minutes.',
    ],
    ingredients: [
      { label: 'Thon au naturel', searchTerm: 'thon au naturel', quantityG: 200 },
      { label: 'Haricots blancs', searchTerm: 'haricot blanc cuit', quantityG: 300 },
      { label: 'Tomates', searchTerm: 'tomate rouge crue', quantityG: 200 },
      { label: 'Oignon rouge', searchTerm: 'oignon cru', quantityG: 50 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
      { label: 'Vinaigre balsamique', searchTerm: 'vinaigre balsamique', quantityG: 15 },
    ],
    estimate: { kcal: 413, proteinG: 38 },
  },
  {
    slug: 'lose-bowl-pois-chiches-patate-douce',
    name: 'Bowl pois chiches et patate douce',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Préchauffer le four à 200 °C.',
      'Couper les patates douces en cubes, les huiler, les enfourner 25 minutes.',
      'Faire revenir les pois chiches égouttés 5 minutes à la poêle, avec du paprika.',
      'Dresser sur un lit d’épinards, émietter la feta par-dessus.',
    ],
    ingredients: [
      { label: 'Pois chiches', searchTerm: 'pois chiche cuit', quantityG: 300 },
      { label: 'Patates douces', searchTerm: 'patate douce cuite', quantityG: 350 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 200 },
      { label: 'Feta', searchTerm: 'feta', quantityG: 60 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 533, proteinG: 23 },
  },
  {
    slug: 'lose-cabillaud-riz-complet',
    name: 'Cabillaud vapeur, riz complet et haricots verts',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre le riz complet à cuire, 20 minutes.',
      'Poser les dos de cabillaud dans le panier vapeur, 10 minutes, avec des rondelles de citron.',
      'Cuire les haricots verts 8 minutes à la vapeur eux aussi.',
      'Servir arrosé d’un filet d’huile d’olive et du reste de citron.',
    ],
    ingredients: [
      { label: 'Dos de cabillaud', searchTerm: 'cabillaud cuit', quantityG: 280 },
      { label: 'Riz complet', searchTerm: 'riz complet cuit', quantityG: 250 },
      { label: 'Haricots verts', searchTerm: 'haricot vert cuit', quantityG: 300 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 10 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 20 },
    ],
    estimate: { kcal: 474, proteinG: 42 },
  },
  {
    slug: 'lose-salade-lentilles-oeuf',
    name: 'Salade de lentilles, œuf dur et crudités',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Cuire les lentilles 20 minutes à l’eau non salée, les égoutter, les laisser tiédir.',
      'Cuire les œufs 9 minutes, les écaler, les couper en deux.',
      'Râper les carottes, couper le concombre et les tomates en dés.',
      'Fouetter la moutarde avec l’huile, mélanger le tout.',
    ],
    ingredients: [
      { label: 'Lentilles vertes', searchTerm: 'lentille cuite', quantityG: 300 },
      { label: 'Œufs', searchTerm: 'oeuf dur', quantityG: 100, unitName: 'œuf', unitGrams: 50 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 150 },
      { label: 'Concombre', searchTerm: 'concombre cru', quantityG: 150 },
      { label: 'Tomates', searchTerm: 'tomate rouge crue', quantityG: 150 },
      { label: 'Moutarde', searchTerm: 'moutarde', quantityG: 10 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 10 },
    ],
    estimate: { kcal: 355, proteinG: 24 },
  },
  {
    slug: 'lose-wok-dinde-legumes',
    name: 'Wok de dinde et légumes croquants',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Mettre le riz basmati à cuire.',
      'Couper la dinde en lanières, la saisir 4 minutes à feu très vif.',
      'Ajouter poivrons, brocolis et champignons, sauter 6 minutes en remuant sans cesse.',
      'Râper le gingembre par-dessus, servir immédiatement avec le riz.',
    ],
    ingredients: [
      { label: 'Escalopes de dinde', searchTerm: 'dinde escalope cuite', quantityG: 260 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 200 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 250 },
      { label: 'Champignons de Paris', searchTerm: 'champignon de paris cru', quantityG: 150 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 200 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 15 },
      { label: 'Gingembre frais', searchTerm: 'gingembre frais', quantityG: 10 },
    ],
    estimate: { kcal: 484, proteinG: 50 },
  },
  {
    slug: 'lose-poulet-ratatouille',
    name: 'Poulet rôti et ratatouille',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Faire revenir l’oignon émincé 5 minutes à l’huile d’olive.',
      'Ajouter aubergines et courgettes en cubes, cuire 10 minutes à feu vif.',
      'Verser les tomates pelées, laisser mijoter 15 minutes à couvert.',
      'Enfourner les cuisses de poulet à 200 °C pendant 30 minutes, servir avec les pommes de terre.',
    ],
    ingredients: [
      { label: 'Cuisses de poulet', searchTerm: 'poulet roti viande', quantityG: 280 },
      { label: 'Aubergines', searchTerm: 'aubergine cuite', quantityG: 250 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 250 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 200 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 80 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 473, proteinG: 40 },
  },
  {
    slug: 'lose-taboule-chou-fleur-poulet',
    name: 'Taboulé de chou-fleur au poulet',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Mixer le chou-fleur cru par à-coups, jusqu’à obtenir la taille d’une semoule.',
      'Couper tomates et concombre en petits dés, les mélanger au chou-fleur.',
      'Ajouter les pois chiches et le poulet poêlé coupé en cubes.',
      'Assaisonner d’huile d’olive et de jus de citron, laisser reposer 15 minutes au frais.',
    ],
    ingredients: [
      { label: 'Chou-fleur', searchTerm: 'chou fleur cru', quantityG: 400 },
      { label: 'Filets de poulet', searchTerm: 'filet de poulet cuit a la poele', quantityG: 240 },
      { label: 'Pois chiches', searchTerm: 'pois chiche cuit', quantityG: 150 },
      { label: 'Tomates', searchTerm: 'tomate rouge crue', quantityG: 200 },
      { label: 'Concombre', searchTerm: 'concombre cru', quantityG: 150 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 30 },
    ],
    estimate: { kcal: 432, proteinG: 47 },
  },
  {
    slug: 'lose-soupe-legumes-dinde',
    name: 'Soupe de légumes et blanc de dinde',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Couper poireaux, carottes et céleri en morceaux, les couvrir d’eau.',
      'Cuire 25 minutes à frémissement, saler en fin de cuisson.',
      'Mixer la moitié du bouillon, laisser l’autre en morceaux : la soupe tient mieux au corps.',
      'Ajouter la dinde rôtie effilochée et les pommes de terre au moment de servir.',
    ],
    ingredients: [
      { label: 'Poireaux', searchTerm: 'poireau cuit', quantityG: 250 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 250 },
      { label: 'Céleri-rave', searchTerm: 'celeri rave cuit', quantityG: 200 },
      { label: 'Blanc de dinde', searchTerm: 'dinde blanc cuit', quantityG: 200 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 250 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 10 },
    ],
    estimate: { kcal: 402, proteinG: 37 },
  },
  {
    slug: 'lose-saumon-papillote-brocolis',
    name: 'Saumon en papillote et brocolis',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Préchauffer le four à 200 °C.',
      'Poser chaque pavé de saumon sur une feuille de papier cuisson, arroser de citron, fermer la papillote.',
      'Enfourner 15 minutes.',
      'Cuire les brocolis 8 minutes à la vapeur, servir avec le riz et un filet d’huile.',
    ],
    ingredients: [
      { label: 'Pavés de saumon', searchTerm: 'saumon cuit vapeur', quantityG: 240 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 350 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 150 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 20 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 10 },
    ],
    estimate: { kcal: 464, proteinG: 37 },
  },
  {
    slug: 'lose-crevettes-ail-courgettes',
    name: 'Crevettes à l’ail et courgettes',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Mettre le boulgour à gonfler dans deux fois son volume d’eau bouillante.',
      'Faire blondir l’ail haché dans l’huile d’olive, 1 minute, sans le brûler.',
      'Ajouter les courgettes en rondelles, cuire 8 minutes à feu vif.',
      'Jeter les crevettes en fin de cuisson, 3 minutes, pas davantage.',
    ],
    ingredients: [
      { label: 'Crevettes', searchTerm: 'crevette cuite', quantityG: 250 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 400 },
      { label: 'Boulgour', searchTerm: 'boulgour cuit', quantityG: 200 },
      { label: 'Ail', searchTerm: 'ail cru', quantityG: 15 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 352, proteinG: 32 },
  },
  {
    slug: 'lose-curry-lentilles-corail',
    name: 'Curry de lentilles corail aux épinards',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Faire revenir l’oignon émincé, ajouter le curry, laisser griller 30 secondes.',
      'Verser les lentilles corail et deux fois leur volume d’eau, cuire 15 minutes.',
      'Ajouter le lait de coco et les épinards, laisser fondre 3 minutes.',
      'Servir avec le riz basmati.',
    ],
    ingredients: [
      { label: 'Lentilles corail', searchTerm: 'lentille corail cuite', quantityG: 350 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 250 },
      { label: 'Lait de coco', searchTerm: 'lait de coco', quantityG: 100 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 150 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 80 },
      { label: 'Curry en poudre', searchTerm: 'curry poudre', quantityG: 8 },
    ],
    estimate: { kcal: 478, proteinG: 27 },
  },
  {
    slug: 'lose-gratin-chou-fleur-jambon',
    name: 'Gratin de chou-fleur au jambon',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Cuire le chou-fleur en bouquets 12 minutes à l’eau bouillante salée.',
      'Fouetter le lait avec la moutarde, saler, poivrer, muscader.',
      'Disposer chou-fleur, pommes de terre et jambon en dés dans un plat, napper de sauce.',
      'Couvrir d’emmental râpé, enfourner 20 minutes à 200 °C.',
    ],
    ingredients: [
      { label: 'Chou-fleur', searchTerm: 'chou fleur cru', quantityG: 600 },
      { label: 'Jambon blanc', searchTerm: 'jambon cuit decouenne tranche', quantityG: 150 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 200 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 60 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 150 },
      { label: 'Moutarde', searchTerm: 'moutarde', quantityG: 10 },
    ],
    estimate: { kcal: 397, proteinG: 34 },
  },
  {
    slug: 'lose-tofu-legumes-verts',
    name: 'Tofu sauté aux légumes verts',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Presser le tofu entre deux feuilles de papier absorbant, le couper en cubes.',
      'Le saisir 8 minutes à l’huile de colza, en le retournant peu : il doit dorer.',
      'Ajouter haricots verts et brocolis, sauter 5 minutes.',
      'Parsemer de graines de sésame grillées.',
    ],
    ingredients: [
      { label: 'Tofu nature', searchTerm: 'tofu nature', quantityG: 300 },
      { label: 'Haricots verts', searchTerm: 'haricot vert cuit', quantityG: 300 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 200 },
      { label: 'Graines de sésame', searchTerm: 'sesame graine', quantityG: 15 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 15 },
    ],
    estimate: { kcal: 416, proteinG: 29 },
  },
  {
    slug: 'lose-colin-puree-celeri',
    name: 'Colin et purée de céleri',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Cuire céleri-rave et pommes de terre en cubes 20 minutes à l’eau salée.',
      'Les écraser avec le lait chaud et le beurre, saler, poivrer.',
      'Poêler les filets de colin 4 minutes de chaque côté.',
      'Servir le poisson sur la purée.',
    ],
    ingredients: [
      { label: 'Filets de colin', searchTerm: 'colin cuit', quantityG: 280 },
      { label: 'Céleri-rave', searchTerm: 'celeri rave cuit', quantityG: 400 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 250 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 100 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 10 },
    ],
    estimate: { kcal: 373, proteinG: 41 },
  },
  {
    slug: 'lose-steak-hache-haricots-verts',
    name: 'Steak haché 5 % et haricots verts',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 15,
    steps: [
      'Faire revenir l’oignon émincé 5 minutes à l’huile d’olive.',
      'Ajouter les haricots verts déjà cuits, réchauffer 3 minutes avec l’oignon.',
      'Saisir les steaks 2 minutes par face à feu vif, saler après cuisson.',
      'Servir avec les pommes de terre en robe des champs.',
    ],
    ingredients: [
      { label: 'Steaks hachés 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 250 },
      { label: 'Haricots verts', searchTerm: 'haricot vert cuit', quantityG: 400 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 200 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 60 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 10 },
    ],
    estimate: { kcal: 390, proteinG: 38 },
  },
  {
    slug: 'lose-fromage-blanc-amandes',
    name: 'Fromage blanc, amandes et cannelle',
    slot: 'snack',
    servings: 1,
    prepMinutes: 2,
    steps: ['Mélanger la cannelle au fromage blanc, parsemer d’amandes concassées.'],
    ingredients: [
      { label: 'Fromage blanc 0 %', searchTerm: 'fromage blanc 0', quantityG: 200 },
      { label: 'Amandes', searchTerm: 'amande emondee', quantityG: 20 },
      { label: 'Cannelle', searchTerm: 'cannelle', quantityG: 1 },
    ],
    estimate: { kcal: 225, proteinG: 19 },
  },
  {
    slug: 'lose-pomme-beurre-cacahuete',
    name: 'Pomme et beurre de cacahuète',
    slot: 'snack',
    servings: 1,
    prepMinutes: 2,
    steps: [
      'Couper la pomme en quartiers épais.',
      'Y étaler le beurre de cacahuète, une cuillère à café par quartier.',
    ],
    ingredients: [
      { label: 'Pomme', searchTerm: 'pomme crue', quantityG: 150, unitName: 'pomme', unitGrams: 150 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 20 },
    ],
    estimate: { kcal: 210, proteinG: 5 },
  },
  {
    slug: 'lose-oeufs-durs-carottes',
    name: 'Œufs durs et bâtonnets de carotte',
    slot: 'snack',
    servings: 1,
    prepMinutes: 2,
    steps: [
      'Écaler les œufs cuits d’avance, les saler légèrement.',
      'Tailler les carottes en bâtonnets.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf dur', quantityG: 100, unitName: 'œuf', unitGrams: 50 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 120 },
    ],
    estimate: { kcal: 170, proteinG: 14 },
  },
];
