import type { CatalogMeal } from '../meal-catalog';

/**
 * Les plats de l'objectif « maintien ».
 *
 * Ni restriction ni surcharge : un féculent, une protéine, un légume, et de
 * quoi tenir jusqu'au repas suivant. C'est la famille la plus large des trois,
 * et celle dont les plats servent aussi de base aux deux autres — on y ajoute
 * ou on y retranche, on ne recommence pas.
 *
 * Les estimations sont recalculées par `npm run verify:catalog` (voir
 * `meal-catalog.ts`). Ne pas les corriger à la main.
 */
export const CATALOG_MAINTAIN: readonly CatalogMeal[] = [
  {
    slug: 'maintain-porridge-banane-cacahuete',
    name: 'Porridge banane et beurre de cacahuète',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 8,
    steps: [
      'Porter le lait à frémissement, y verser les flocons d’avoine.',
      'Cuire 5 minutes en remuant jusqu’à épaississement.',
      'Écraser la banane dans le porridge, hors du feu.',
      'Faire fondre le beurre de cacahuète par-dessus.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 60 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 250 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 120, unitName: 'banane', unitGrams: 120 },
      { label: 'Beurre de cacahuète', searchTerm: 'beurre de cacahuete', quantityG: 15 },
    ],
    estimate: { kcal: 542, proteinG: 20 },
  },
  {
    slug: 'maintain-tartines-oeufs-avocat',
    name: 'Tartines d’œufs brouillés et avocat',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 10,
    steps: [
      'Battre les œufs, les cuire à feu très doux en remuant sans arrêt, 4 minutes.',
      'Griller les tranches de pain.',
      'Écraser l’avocat dessus, ajouter les œufs et les tranches de tomate.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 80 },
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 120, unitName: 'œuf', unitGrams: 60 },
      { label: 'Avocat', searchTerm: 'avocat cru', quantityG: 60 },
      { label: 'Tomate', searchTerm: 'tomate rouge crue', quantityG: 80 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 5 },
    ],
    estimate: { kcal: 551, proteinG: 23 },
  },
  {
    slug: 'maintain-bol-yaourt-granola',
    name: 'Bol de yaourt grec, avoine grillée et fraises',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 10,
    steps: [
      'Griller les flocons d’avoine à sec 4 minutes, avec le miel, jusqu’à ce qu’ils dorent.',
      'Les laisser refroidir : c’est en refroidissant qu’ils croustillent.',
      'Verser sur le yaourt, ajouter fraises et noix concassées.',
    ],
    ingredients: [
      { label: 'Yaourt grec nature', searchTerm: 'yaourt grec nature', quantityG: 200 },
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 40 },
      { label: 'Cerneaux de noix', searchTerm: 'noix cerneaux', quantityG: 15 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 15 },
      { label: 'Fraises', searchTerm: 'fraise crue', quantityG: 100 },
    ],
    estimate: { kcal: 545, proteinG: 13 },
  },
  {
    slug: 'maintain-pancakes-avoine',
    name: 'Pancakes à l’avoine et au fromage blanc',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 15,
    steps: [
      'Mixer flocons d’avoine, œufs, fromage blanc et la moitié de la banane.',
      'Laisser reposer la pâte 5 minutes.',
      'Cuire de petites louches 2 minutes par face à feu moyen, dans un peu d’huile.',
      'Servir avec le reste de banane en rondelles.',
    ],
    ingredients: [
      { label: 'Flocons d’avoine', searchTerm: 'flocons d avoine', quantityG: 60 },
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 100, unitName: 'œuf', unitGrams: 50 },
      { label: 'Fromage blanc 3 %', searchTerm: 'fromage blanc 3', quantityG: 100 },
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 100, unitName: 'banane', unitGrams: 100 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 5 },
    ],
    estimate: { kcal: 570, proteinG: 28 },
  },
  {
    slug: 'maintain-pain-jambon-fromage-blanc',
    name: 'Pain, jambon et fromage blanc',
    slot: 'breakfast',
    servings: 1,
    prepMinutes: 5,
    steps: [
      'Griller le pain.',
      'Y déposer les tranches de jambon.',
      'Servir avec le fromage blanc et l’orange en quartiers.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 80 },
      { label: 'Jambon blanc', searchTerm: 'jambon cuit decouenne tranche', quantityG: 80 },
      { label: 'Fromage blanc 3 %', searchTerm: 'fromage blanc 3', quantityG: 100 },
      { label: 'Orange', searchTerm: 'orange crue', quantityG: 150, unitName: 'orange', unitGrams: 150 },
    ],
    estimate: { kcal: 435, proteinG: 31 },
  },
  {
    slug: 'maintain-poulet-riz-poivrons',
    name: 'Poulet, riz basmati et poivrons',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre le riz à cuire.',
      'Faire revenir l’oignon et les poivrons en lanières 10 minutes à l’huile d’olive.',
      'Poêler les filets de poulet 5 minutes par face, les trancher.',
      'Réunir le tout dans la poêle, une minute, pour que les sucs se mélangent.',
    ],
    ingredients: [
      { label: 'Filets de poulet', searchTerm: 'filet de poulet cuit a la poele', quantityG: 280 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 400 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 250 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 80 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 627, proteinG: 50 },
  },
  {
    slug: 'maintain-pates-thon-tomates',
    name: 'Pâtes au thon et tomates',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Mettre les pâtes à cuire dans un grand volume d’eau salée.',
      'Faire blondir l’ail haché à l’huile d’olive, verser les tomates pelées, mijoter 10 minutes.',
      'Ajouter le thon égoutté en fin de cuisson, sans l’écraser.',
      'Mélanger aux pâtes égouttées, râper le parmesan par-dessus.',
    ],
    ingredients: [
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 400 },
      { label: 'Thon au naturel', searchTerm: 'thon au naturel', quantityG: 200 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 250 },
      { label: 'Parmesan', searchTerm: 'parmesan', quantityG: 30 },
      { label: 'Ail', searchTerm: 'ail cru', quantityG: 10 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 679, proteinG: 48 },
  },
  {
    slug: 'maintain-chili-boeuf-haricots',
    name: 'Chili de bœuf aux haricots rouges',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Saisir la viande hachée à feu vif, l’émietter à la spatule.',
      'Ajouter poivrons en dés et tomates pelées, laisser mijoter 20 minutes.',
      'Verser les haricots rouges rincés, réchauffer 5 minutes.',
      'Servir sur le riz blanc.',
    ],
    ingredients: [
      { label: 'Bœuf haché 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 250 },
      { label: 'Haricots rouges', searchTerm: 'haricot rouge cuit', quantityG: 350 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 250 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 150 },
      { label: 'Riz blanc', searchTerm: 'riz blanc cuit', quantityG: 250 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 695, proteinG: 54 },
  },
  {
    slug: 'maintain-salade-quinoa-feta',
    name: 'Salade de quinoa, pois chiches et feta',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Cuire le quinoa 15 minutes, le rincer à l’eau froide pour l’arrêter.',
      'Couper concombre et tomates en dés.',
      'Mélanger avec les pois chiches rincés et l’huile d’olive.',
      'Émietter la feta au dernier moment, pour qu’elle reste en morceaux.',
    ],
    ingredients: [
      { label: 'Quinoa', searchTerm: 'quinoa cuit', quantityG: 350 },
      { label: 'Pois chiches', searchTerm: 'pois chiche cuit', quantityG: 250 },
      { label: 'Feta', searchTerm: 'feta', quantityG: 80 },
      { label: 'Concombre', searchTerm: 'concombre cru', quantityG: 200 },
      { label: 'Tomates', searchTerm: 'tomate rouge crue', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 684, proteinG: 26 },
  },
  {
    slug: 'maintain-saumon-pommes-terre',
    name: 'Saumon, pommes de terre et haricots verts',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Cuire les pommes de terre 20 minutes à l’eau salée.',
      'Cuire les haricots verts 8 minutes à la vapeur.',
      'Poêler les pavés de saumon côté peau 5 minutes, puis 2 minutes sur l’autre face.',
      'Arroser de citron, servir avec une noisette de beurre sur les pommes de terre.',
    ],
    ingredients: [
      { label: 'Pavés de saumon', searchTerm: 'saumon pave cuit', quantityG: 260 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 400 },
      { label: 'Haricots verts', searchTerm: 'haricot vert cuit', quantityG: 300 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 10 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
      { label: 'Jus de citron', searchTerm: 'citron jus', quantityG: 20 },
    ],
    estimate: { kcal: 581, proteinG: 37 },
  },
  {
    slug: 'maintain-boulgour-dinde-legumes',
    name: 'Boulgour, dinde et légumes rôtis',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Préchauffer le four à 210 °C.',
      'Couper courgettes et aubergines en cubes, les huiler, les enfourner 25 minutes.',
      'Faire gonfler le boulgour dans deux fois son volume d’eau bouillante, 12 minutes à couvert.',
      'Poêler les escalopes de dinde 4 minutes par face, les trancher, tout mélanger.',
    ],
    ingredients: [
      { label: 'Escalopes de dinde', searchTerm: 'dinde escalope cuite', quantityG: 280 },
      { label: 'Boulgour', searchTerm: 'boulgour cuit', quantityG: 350 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 250 },
      { label: 'Aubergines', searchTerm: 'aubergine cuite', quantityG: 250 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 567, proteinG: 52 },
  },
  {
    slug: 'maintain-omelette-pommes-terre',
    name: 'Omelette aux pommes de terre',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Faire rissoler les pommes de terre en rondelles et l’oignon 15 minutes à l’huile d’olive.',
      'Battre les œufs, les verser sur les pommes de terre, baisser le feu.',
      'Cuire 6 minutes à couvert, parsemer d’emmental, laisser fondre.',
      'Servir avec la salade verte.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 240, unitName: 'œuf', unitGrams: 60 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 450 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 40 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 80 },
      { label: 'Salade verte', searchTerm: 'salade verte laitue', quantityG: 100 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 20 },
    ],
    estimate: { kcal: 536, proteinG: 26 },
  },
  {
    slug: 'maintain-curry-poulet-coco',
    name: 'Curry de poulet au lait de coco',
    slot: 'lunch',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Faire revenir l’oignon, ajouter le curry, laisser griller 30 secondes.',
      'Saisir les morceaux de poulet 5 minutes.',
      'Verser le lait de coco et les poivrons, mijoter 15 minutes à découvert.',
      'Servir sur le riz basmati.',
    ],
    ingredients: [
      { label: 'Cuisses de poulet', searchTerm: 'poulet roti viande', quantityG: 280 },
      { label: 'Lait de coco', searchTerm: 'lait de coco', quantityG: 150 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 350 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 150 },
      { label: 'Oignon', searchTerm: 'oignon cru', quantityG: 80 },
      { label: 'Curry en poudre', searchTerm: 'curry poudre', quantityG: 8 },
    ],
    estimate: { kcal: 692, proteinG: 43 },
  },
  {
    slug: 'maintain-gratin-courgettes-jambon',
    name: 'Gratin de courgettes au jambon',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Faire dégorger les courgettes en rondelles 10 minutes à la poêle, à sec.',
      'Mélanger le riz cuit, le jambon en dés, les courgettes, le lait et la crème.',
      'Verser dans un plat, couvrir d’emmental.',
      'Enfourner 20 minutes à 200 °C, jusqu’à ce que le dessus soit doré.',
    ],
    ingredients: [
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 500 },
      { label: 'Jambon blanc', searchTerm: 'jambon cuit decouenne tranche', quantityG: 150 },
      { label: 'Riz blanc', searchTerm: 'riz blanc cuit', quantityG: 250 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 60 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 150 },
      { label: 'Crème épaisse', searchTerm: 'creme fraiche epaisse', quantityG: 40 },
    ],
    estimate: { kcal: 523, proteinG: 33 },
  },
  {
    slug: 'maintain-truite-semoule-legumes',
    name: 'Truite, semoule et légumes',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Verser l’eau bouillante sur la semoule, à hauteur, couvrir 5 minutes.',
      'Faire revenir carottes et courgettes en petits dés 10 minutes à l’huile d’olive.',
      'Cuire les filets de truite au four 12 minutes à 190 °C.',
      'Égrener la semoule à la fourchette, y mêler les légumes.',
    ],
    ingredients: [
      { label: 'Filets de truite', searchTerm: 'truite cuite', quantityG: 260 },
      { label: 'Semoule', searchTerm: 'semoule cuite', quantityG: 300 },
      { label: 'Courgettes', searchTerm: 'courgette cuite', quantityG: 250 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 150 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 593, proteinG: 45 },
  },
  {
    slug: 'maintain-soupe-lentilles-lardons',
    name: 'Soupe de lentilles aux lardons',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 35,
    steps: [
      'Faire dorer les lardons à sec dans la cocotte, les réserver.',
      'Y faire suer poireaux et carottes en rondelles, 8 minutes.',
      'Ajouter les lentilles et un litre d’eau, cuire 25 minutes.',
      'Remettre les lardons en fin de cuisson, servir avec le pain.',
    ],
    ingredients: [
      { label: 'Lentilles vertes', searchTerm: 'lentille cuite', quantityG: 400 },
      { label: 'Lardons fumés', searchTerm: 'lardon fume', quantityG: 80 },
      { label: 'Poireaux', searchTerm: 'poireau cuit', quantityG: 250 },
      { label: 'Carottes', searchTerm: 'carotte crue', quantityG: 200 },
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 100 },
    ],
    estimate: { kcal: 546, proteinG: 35 },
  },
  {
    slug: 'maintain-tofu-nouilles-legumes',
    name: 'Tofu sauté, nouilles et brocolis',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 25,
    steps: [
      'Mettre les pâtes à cuire.',
      'Saisir le tofu en cubes 8 minutes à l’huile de colza, jusqu’à ce qu’il dore.',
      'Ajouter les brocolis, sauter 5 minutes à feu vif.',
      'Mélanger aux pâtes égouttées, parsemer de sésame.',
    ],
    ingredients: [
      { label: 'Tofu nature', searchTerm: 'tofu nature', quantityG: 300 },
      { label: 'Pâtes complètes', searchTerm: 'pates blanches cuites', quantityG: 300 },
      { label: 'Brocolis', searchTerm: 'brocoli cuit', quantityG: 250 },
      { label: 'Graines de sésame', searchTerm: 'sesame graine', quantityG: 15 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 20 },
    ],
    estimate: { kcal: 672, proteinG: 38 },
  },
  {
    slug: 'maintain-cabillaud-ecrase-pommes-terre',
    name: 'Cabillaud et écrasé de pommes de terre',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Cuire les pommes de terre 20 minutes à l’eau salée, les écraser grossièrement avec le lait et le beurre.',
      'Faire tomber les épinards 3 minutes à l’huile d’olive.',
      'Poêler le cabillaud 4 minutes de chaque côté, à feu moyen.',
      'Dresser le poisson sur l’écrasé, les épinards à côté.',
    ],
    ingredients: [
      { label: 'Dos de cabillaud', searchTerm: 'cabillaud cuit', quantityG: 300 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 450 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 250 },
      { label: 'Beurre', searchTerm: 'beurre doux', quantityG: 20 },
      { label: 'Lait demi-écrémé', searchTerm: 'lait demi ecreme', quantityG: 100 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 10 },
    ],
    estimate: { kcal: 510, proteinG: 47 },
  },
  {
    slug: 'maintain-poivrons-farcis',
    name: 'Poivrons farcis au bœuf et au riz',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 45,
    steps: [
      'Couper les poivrons en deux, les épépiner, les précuire 10 minutes au four à 200 °C.',
      'Mélanger la viande saisie, le riz cuit et les tomates pelées.',
      'Garnir les poivrons, couvrir d’emmental.',
      'Enfourner 25 minutes à 190 °C.',
    ],
    ingredients: [
      { label: 'Bœuf haché 5 %', searchTerm: 'steak hache 5% cuit', quantityG: 250 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 400 },
      { label: 'Riz blanc', searchTerm: 'riz blanc cuit', quantityG: 250 },
      { label: 'Tomates pelées', searchTerm: 'tomate pelee', quantityG: 200 },
      { label: 'Emmental râpé', searchTerm: 'fromage rape emmental', quantityG: 40 },
    ],
    estimate: { kcal: 523, proteinG: 44 },
  },
  {
    slug: 'maintain-frittata-legumes-feta',
    name: 'Frittata aux légumes et à la feta',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 30,
    steps: [
      'Faire rissoler les pommes de terre en dés 12 minutes à l’huile d’olive.',
      'Ajouter les épinards, laisser rendre leur eau.',
      'Verser les œufs battus, émietter la feta dessus.',
      'Cuire 8 minutes à couvert, puis 3 minutes sous le gril pour dorer.',
    ],
    ingredients: [
      { label: 'Œufs', searchTerm: 'oeuf entier cru', quantityG: 300, unitName: 'œuf', unitGrams: 60 },
      { label: 'Pommes de terre', searchTerm: 'pomme de terre cuite eau', quantityG: 350 },
      { label: 'Feta', searchTerm: 'feta', quantityG: 80 },
      { label: 'Épinards', searchTerm: 'epinard cuit', quantityG: 200 },
      { label: 'Huile d’olive', searchTerm: 'huile d olive', quantityG: 15 },
    ],
    estimate: { kcal: 552, proteinG: 32 },
  },
  {
    slug: 'maintain-wok-crevettes-riz',
    name: 'Wok de crevettes, riz et petits pois',
    slot: 'dinner',
    servings: 2,
    prepMinutes: 20,
    steps: [
      'Faire sauter les poivrons en lanières 5 minutes à feu vif.',
      'Ajouter le riz déjà cuit et les petits pois, remuer 3 minutes.',
      'Jeter les crevettes, râper le gingembre, 3 minutes de plus.',
      'Servir aussitôt : les crevettes durcissent si elles attendent.',
    ],
    ingredients: [
      { label: 'Crevettes', searchTerm: 'crevette cuite', quantityG: 280 },
      { label: 'Riz basmati', searchTerm: 'riz basmati cuit', quantityG: 350 },
      { label: 'Petits pois', searchTerm: 'petit pois cuit', quantityG: 200 },
      { label: 'Poivrons', searchTerm: 'poivron cru', quantityG: 150 },
      { label: 'Huile de colza', searchTerm: 'huile de colza', quantityG: 15 },
      { label: 'Gingembre frais', searchTerm: 'gingembre frais', quantityG: 10 },
    ],
    estimate: { kcal: 534, proteinG: 40 },
  },
  {
    slug: 'maintain-yaourt-noix-miel',
    name: 'Yaourt grec, noix et miel',
    slot: 'snack',
    servings: 1,
    prepMinutes: 2,
    steps: ['Concasser les noix sur le yaourt, filer le miel par-dessus.'],
    ingredients: [
      { label: 'Yaourt grec nature', searchTerm: 'yaourt grec nature', quantityG: 200 },
      { label: 'Cerneaux de noix', searchTerm: 'noix cerneaux', quantityG: 15 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 15 },
    ],
    estimate: { kcal: 362, proteinG: 8 },
  },
  {
    slug: 'maintain-banane-amandes',
    name: 'Banane et amandes',
    slot: 'snack',
    servings: 1,
    prepMinutes: 1,
    steps: ['Rien à préparer. C’est tout l’intérêt.'],
    ingredients: [
      { label: 'Banane', searchTerm: 'banane chair crue', quantityG: 150, unitName: 'banane', unitGrams: 150 },
      { label: 'Amandes', searchTerm: 'amande emondee', quantityG: 25 },
    ],
    estimate: { kcal: 289, proteinG: 7 },
  },
  {
    slug: 'maintain-tartine-fromage-blanc-miel',
    name: 'Tartine de fromage blanc au miel',
    slot: 'snack',
    servings: 1,
    prepMinutes: 3,
    steps: [
      'Griller le pain.',
      'Y étaler le fromage blanc épais, filer le miel dessus.',
    ],
    ingredients: [
      { label: 'Pain de campagne', searchTerm: 'pain de campagne', quantityG: 60 },
      { label: 'Fromage blanc 3 %', searchTerm: 'fromage blanc 3', quantityG: 120 },
      { label: 'Miel', searchTerm: 'miel', quantityG: 10 },
    ],
    estimate: { kcal: 276, proteinG: 13 },
  },
];
